name: build multiarch image

on:
  push:
    branches:
      - '[1-9].[1-9]'
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        env:
          DOCKER_ORG: zurajm
          DOCKER_PREFIX: mailu-
          MAILU_VERSION: ${GITHUB_REF##*/}
        run: |
          docker buildx bake \
            --file tests/build.yml \
            --set '*.platform=linux/amd64,linux/arm/v7,linux/arm64' \
            --push