name: build multiarch image

on:
  push:
    branches:
      - '[1-9].[1-9]'
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: build the image
        env:
          DOCKER_ORG: zurajm
          DOCKER_PREFIX: mailu-
          # MAILU_VERSION: ${GITHUB_REF##*/}
        run: |
          export MAILU_VERSION=${GITHUB_REF##*/}
          pushd ./tests
          docker buildx bake \
            --file build.yml \
            --set '*.platform=linux/amd64,linux/arm/v7,linux/arm64' \
            --push